import type { PhotoInput } from '@/lib/photography'

// src is a Bunny-relative base path (no leading slash, no extension) so
// lib/photography can append `-<width>.webp` to reach each pre-encoded variant.
// Files live under /photos on the images zone.
export const photographyManifest: PhotoInput[] = [
  {
    slug: '01',
    src: 'photos/01',
    alt: 'Person sitting on a park bench beside a bronze monument among bare winter trees',
    location: 'Montréal, Canada',
    width: 1440,
    height: 955,
  },
  {
    slug: '02',
    src: 'photos/02',
    alt: 'A rope-and-post fence runs along a grassy clifftop above a calm sea at dusk',
    location: 'Percé, Canada',
    width: 1440,
    height: 1419,
  },
  {
    slug: '03',
    src: 'photos/03',
    alt: 'A weathered gray barn on a hillside of rust-colored autumn brush under a clear sky',
    location: 'Percé, Canada',
    width: 1440,
    height: 1419,
  },
  {
    slug: '04',
    src: 'photos/04',
    alt: 'A pebble beach curves beneath a forested cliff streaked with autumn yellow',
    location: 'Forillon, Gaspésie',
    width: 1440,
    height: 1419,
  },
  {
    slug: '05',
    src: 'photos/05',
    alt: 'A flat-topped sea rock glows at golden hour above still, mirror-like water',
    location: 'Percé, Canada',
    width: 1440,
    height: 1419,
  },
  {
    slug: '06',
    src: 'photos/06',
    alt: 'A white lighthouse with red trim stands on a grassy headland under a clear blue sky',
    location: 'Carleton-Sur-Mer, Canada',
    width: 1440,
    height: 1419,
  },
  {
    slug: '07',
    src: 'photos/07',
    alt: 'Black-and-white portrait of a border collie lying on stone pavers, gazing up at the camera',
    location: 'Montréal, Canada',
    width: 1440,
    height: 955,
  },
  {
    slug: '08',
    src: 'photos/08',
    alt: 'Red paper lanterns hang from the branches of a leafy tree',
    location: 'Montréal, Canada',
    width: 1440,
    height: 955,
  },
  {
    slug: '09',
    src: 'photos/09',
    alt: 'Paint cans, rollers, and trays scattered on concrete during a painting job',
    location: 'Montréal, Canada',
    width: 1440,
    height: 1419,
  },
  {
    slug: '10',
    src: 'photos/10',
    alt: 'Black-and-white view beneath a curving concrete viaduct carried on angled pillars',
    location: 'Montréal, Canada',
    width: 989,
    height: 1440,
  },
  {
    slug: '11',
    src: 'photos/11',
    alt: 'A retired space shuttle orbiter sits in a museum hangar before a large American flag',
    location: 'Virginia, USA',
    width: 960,
    height: 1440,
  },
  {
    slug: '12',
    src: 'photos/12',
    alt: 'A lone figure stands in a sunlit modern atrium crossed by diagonal shadows',
    location: 'Washington, USA',
    width: 960,
    height: 1440,
  },
  {
    slug: '13',
    src: 'photos/13',
    alt: 'Two glass office towers taper upward into a blue sky dotted with cloud reflections',
    location: 'Tokyo, Japan',
    width: 960,
    height: 1440,
  },
  {
    slug: '14',
    src: 'photos/14',
    alt: 'A Manhattan street framing the Empire State Building at dusk, traffic and pedestrians below',
    location: 'New York, USA',
    width: 960,
    height: 1440,
  },
  {
    slug: '15',
    src: 'photos/15',
    alt: 'A quiet paved path curves past sculpted pines and a mossy stone wall',
    location: 'Kyoto, Japan',
    width: 960,
    height: 1440,
  },
  {
    slug: '16',
    src: 'photos/16',
    alt: 'A person stands on a wide gravel courtyard before a green-roofed Japanese shrine, cherry blossom to one side',
    location: 'Kyoto, Japan',
    width: 960,
    height: 1440,
  },
  {
    slug: '17',
    src: 'photos/17',
    alt: 'A cyclist rides along the crest of a green grassy dike against a clear blue sky',
    location: 'Uji, Japan',
    width: 960,
    height: 1440,
  },
  {
    slug: '18',
    src: 'photos/18',
    alt: 'Stone steps and a wooden handrail wind through a mossy green Japanese garden',
    location: 'Nara, Japan',
    width: 960,
    height: 1440,
  },
  {
    slug: '19',
    src: 'photos/19',
    alt: 'A person photographs hanging orange blossoms in a lush greenhouse',
    location: 'Tokyo, Japan',
    width: 960,
    height: 1440,
  },
  {
    slug: '20',
    src: 'photos/20',
    alt: 'A dense bed of mixed flowers blooms beneath trees',
    location: 'Kamakura, Japan',
    width: 960,
    height: 1440,
  },
  {
    slug: '21',
    src: 'photos/21',
    alt: 'Carp-shaped koinobori streamers stretch across a cloud-dappled blue sky',
    location: 'Tokyo, Japan',
    width: 1440,
    height: 960,
  },
  {
    slug: '22',
    src: 'photos/22',
    alt: 'A sweeping concrete wall faces tiers of glass galleries inside a modern atrium',
    location: 'Tokyo, Japan',
    width: 1440,
    height: 960,
  },
  {
    slug: '23',
    src: 'photos/23',
    alt: 'A lifeguard stand and blue umbrella on a wide sandy beach under a bright sky',
    location: 'Albufeira, Portugal',
    width: 1440,
    height: 960,
  },
  {
    slug: '24',
    src: 'photos/24',
    alt: 'An older couple walks past a wall of warm vertical stripes in bright sun',
    location: 'Málaga, Spain',
    width: 960,
    height: 1440,
  },
  {
    slug: '25',
    src: 'photos/25',
    alt: 'Sun-warmed yellow buildings with wrought-iron balconies rise against a clear blue sky',
    location: 'Málaga, Spain',
    width: 960,
    height: 1440,
  },
  {
    slug: '26',
    src: 'photos/26',
    alt: 'Children gather at a snack kiosk beneath a huge flowering chestnut tree',
    location: 'Madrid, Spain',
    width: 960,
    height: 1440,
  },
  {
    slug: '27',
    src: 'photos/27',
    alt: 'Colorful row houses perch above a rocky, grassy slope under a cloud-filled sky',
    location: 'Porto, Portugal',
    width: 960,
    height: 1440,
  },
  {
    slug: '28',
    src: 'photos/28',
    alt: 'Fog rolls over a lush green forested hillside',
    location: 'Sintra, Portugal',
    width: 960,
    height: 1440,
  },
  {
    slug: '29',
    src: 'photos/29',
    alt: 'A red Coca-Cola banner hangs from a salmon-pink stucco wall beside a cloud-reflecting window',
    location: 'Lisbon, Portugal',
    width: 960,
    height: 1440,
  },
  {
    slug: '30',
    src: 'photos/30',
    alt: 'A terracotta building with a tiled roof and chimney stands against a deep blue sky',
    location: 'Lisbon, Portugal',
    width: 960,
    height: 1440,
  },
  {
    slug: '31',
    src: 'photos/31',
    alt: 'A riverside promenade curves past a low white museum toward a red suspension bridge',
    location: 'Lisbon, Portugal',
    width: 1440,
    height: 960,
  },
  {
    slug: '32',
    src: 'photos/32',
    alt: 'Crowds cross a plaza before a grand white triumphal arch under a blue sky',
    location: 'Lisbon, Portugal',
    width: 960,
    height: 1440,
  },
  {
    slug: '33',
    src: 'photos/33',
    alt: 'Strings of colorful bunting flags cross the sky above a crowded outdoor fair',
    location: 'Montréal, Canada',
    width: 960,
    height: 1440,
  },
  {
    slug: '34',
    src: 'photos/34',
    alt: 'Three Shinto priests in white robes walk toward a shrine pavilion among trees',
    location: 'Tokyo, Japan',
    width: 960,
    height: 1440,
  },
  {
    slug: '35',
    src: 'photos/35',
    alt: 'A person in a red jacket walks down a neon-lit night street crowded with signs',
    location: 'Tokyo, Japan',
    width: 960,
    height: 1440,
  },
  {
    slug: '36',
    src: 'photos/36',
    alt: 'Pedestrians cross a busy city intersection lined with modern facades at dusk',
    location: 'Tokyo, Japan',
    width: 1440,
    height: 960,
  },
  {
    slug: '37',
    src: 'photos/37',
    alt: 'A red concept sports car on a showroom floor, a second car behind glass',
    location: 'Tokyo, Japan',
    width: 960,
    height: 1440,
  },
  {
    slug: '38',
    src: 'photos/38',
    alt: 'Silhouettes move among hanging strands of colored light in a dark immersive installation',
    location: 'Tokyo, Japan',
    width: 1440,
    height: 960,
  },
]
