import type { PhotoInput } from '@/lib/photography'

// src paths are Bunny-relative (no leading slash) so lib/photography resolves them
// against images.francois.works. Files live under /photos on the images zone.
export const photographyManifest: PhotoInput[] = [
  {
    slug: 'photo-01',
    src: 'photos/photo-01.jpg',
    alt: 'Person sitting on a park bench beside a bronze monument among bare winter trees',
    location: 'Montréal, Canada',
    width: 1440,
    height: 955,
  },
  {
    slug: 'photo-02',
    src: 'photos/photo-02.jpg',
    alt: 'A rope-and-post fence runs along a grassy clifftop above a calm sea at dusk',
    location: 'Gaspésie, Canada',
    width: 1440,
    height: 1419,
  },
  {
    slug: 'photo-03',
    src: 'photos/photo-03.jpg',
    alt: 'A weathered gray barn on a hillside of rust-colored autumn brush under a clear sky',
    location: 'Percé, Canada',
    width: 1440,
    height: 1419,
  },
  {
    slug: 'photo-04',
    src: 'photos/photo-04.jpg',
    alt: 'A pebble beach curves beneath a forested cliff streaked with autumn yellow',
    location: 'Forillon, Gaspésie',
    width: 1440,
    height: 1419,
  },
  {
    slug: 'photo-05',
    src: 'photos/photo-05.jpg',
    alt: 'A flat-topped sea rock glows at golden hour above still, mirror-like water',
    location: 'Percé, Canada',
    width: 1440,
    height: 1419,
  },
  {
    slug: 'photo-06',
    src: 'photos/photo-06.jpg',
    alt: 'A white lighthouse with red trim stands on a grassy headland under a clear blue sky',
    location: 'Gaspésie, Canada',
    width: 1440,
    height: 1419,
  },
  {
    slug: 'photo-07',
    src: 'photos/photo-07.jpg',
    alt: 'Black-and-white portrait of a border collie lying on stone pavers, gazing up at the camera',
    location: 'Montréal, Canada',
    width: 1440,
    height: 955,
  },
  {
    slug: 'photo-08',
    src: 'photos/photo-08.jpg',
    alt: 'Red paper lanterns hang from the branches of a leafy tree',
    location: 'Montréal, Canada',
    width: 1440,
    height: 955,
  },
  {
    slug: 'photo-09',
    src: 'photos/photo-09.jpg',
    alt: 'Paint cans, rollers, and trays scattered on concrete during a painting job',
    location: 'Montréal, Canada',
    width: 1440,
    height: 1419,
  },
  {
    slug: 'photo-10',
    src: 'photos/photo-10.jpg',
    alt: 'Black-and-white view beneath a curving concrete viaduct carried on angled pillars',
    location: 'Montréal, Canada',
    width: 989,
    height: 1440,
  },
  {
    slug: 'photo-11',
    src: 'photos/photo-11.jpg',
    alt: 'A retired space shuttle orbiter sits in a museum hangar before a large American flag',
    location: 'Virginia, USA',
    width: 960,
    height: 1440,
  },
  {
    slug: 'photo-12',
    src: 'photos/photo-12.jpg',
    alt: 'A lone figure stands in a sunlit modern atrium crossed by diagonal shadows',
    location: 'Washington, USA',
    width: 960,
    height: 1440,
  },
  {
    slug: 'photo-13',
    src: 'photos/photo-13.jpg',
    alt: 'Two glass office towers taper upward into a blue sky dotted with cloud reflections',
    location: 'Tokyo, JP',
    width: 960,
    height: 1440,
  },
  {
    slug: 'photo-14',
    src: 'photos/photo-14.jpg',
    alt: 'A Manhattan street framing the Empire State Building at dusk, traffic and pedestrians below',
    location: 'New York, USA',
    width: 960,
    height: 1440,
  },
  {
    slug: 'photo-15',
    src: 'photos/photo-15.jpg',
    alt: 'A quiet paved path curves past sculpted pines and a mossy stone wall',
    location: 'Kyoto, Japan',
    width: 960,
    height: 1440,
  },
  {
    slug: 'photo-16',
    src: 'photos/photo-16.jpg',
    alt: 'A person stands on a wide gravel courtyard before a green-roofed Japanese shrine, cherry blossom to one side',
    location: 'Kyoto, Japan',
    width: 960,
    height: 1440,
  },
  {
    slug: 'photo-17',
    src: 'photos/photo-17.jpg',
    alt: 'A cyclist rides along the crest of a green grassy dike against a clear blue sky',
    location: 'Uji, Japan',
    width: 960,
    height: 1440,
  },
  {
    slug: 'photo-18',
    src: 'photos/photo-18.jpg',
    alt: 'Stone steps and a wooden handrail wind through a mossy green Japanese garden',
    location: 'Nara, Japan',
    width: 960,
    height: 1440,
  },
  {
    slug: 'photo-19',
    src: 'photos/photo-19.jpg',
    alt: 'A person photographs hanging orange blossoms in a lush greenhouse',
    location: 'Tokyo, Japan',
    width: 960,
    height: 1440,
  },
  {
    slug: 'photo-20',
    src: 'photos/photo-20.jpg',
    alt: 'A dense bed of mixed flowers blooms beneath trees',
    location: 'Kamakura, Japan',
    width: 960,
    height: 1440,
  },
  {
    slug: 'photo-21',
    src: 'photos/photo-21.jpg',
    alt: 'Carp-shaped koinobori streamers stretch across a cloud-dappled blue sky',
    location: 'Tokyo, Japan',
    width: 1440,
    height: 960,
  },
  {
    slug: 'photo-22',
    src: 'photos/photo-22.jpg',
    alt: 'A sweeping concrete wall faces tiers of glass galleries inside a modern atrium',
    location: 'Tokyo, Japan',
    width: 1440,
    height: 960,
  },
  {
    slug: 'photo-23',
    src: 'photos/photo-23.jpg',
    alt: 'A lifeguard stand and blue umbrella on a wide sandy beach under a bright sky',
    location: 'Albufeira, Portugal',
    width: 1440,
    height: 960,
  },
  {
    slug: 'photo-24',
    src: 'photos/photo-24.jpg',
    alt: 'An older couple walks past a wall of warm vertical stripes in bright sun',
    location: 'Málaga, Spain',
    width: 960,
    height: 1440,
  },
  {
    slug: 'photo-25',
    src: 'photos/photo-25.jpg',
    alt: 'Sun-warmed yellow buildings with wrought-iron balconies rise against a clear blue sky',
    location: 'Málaga, Spain',
    width: 960,
    height: 1440,
  },
  {
    slug: 'photo-26',
    src: 'photos/photo-26.jpg',
    alt: 'Children gather at a snack kiosk beneath a huge flowering chestnut tree',
    location: 'Madrid, Spain',
    width: 960,
    height: 1440,
  },
  {
    slug: 'photo-27',
    src: 'photos/photo-27.jpg',
    alt: 'Colorful row houses perch above a rocky, grassy slope under a cloud-filled sky',
    location: 'Porto, Portugal',
    width: 960,
    height: 1440,
  },
  {
    slug: 'photo-28',
    src: 'photos/photo-28.jpg',
    alt: 'Fog rolls over a lush green forested hillside',
    location: 'Sintra, Portugal',
    width: 960,
    height: 1440,
  },
  {
    slug: 'photo-29',
    src: 'photos/photo-29.jpg',
    alt: 'A red Coca-Cola banner hangs from a salmon-pink stucco wall beside a cloud-reflecting window',
    location: 'Lisbon, Portugal',
    width: 960,
    height: 1440,
  },
  {
    slug: 'photo-30',
    src: 'photos/photo-30.jpg',
    alt: 'A terracotta building with a tiled roof and chimney stands against a deep blue sky',
    location: 'Lisbon, Portugal',
    width: 960,
    height: 1440,
  },
  {
    slug: 'photo-31',
    src: 'photos/photo-31.jpg',
    alt: 'A riverside promenade curves past a low white museum toward a red suspension bridge',
    location: 'Lisbon, Portugal',
    width: 1440,
    height: 960,
  },
  {
    slug: 'photo-32',
    src: 'photos/photo-32.jpg',
    alt: 'Crowds cross a plaza before a grand white triumphal arch under a blue sky',
    location: 'Lisbon, Portugal',
    width: 960,
    height: 1440,
  },
  {
    slug: 'photo-33',
    src: 'photos/photo-33.jpg',
    alt: 'Strings of colorful bunting flags cross the sky above a crowded outdoor fair',
    location: 'Montréal, Canada',
    width: 960,
    height: 1440,
  },
  {
    slug: 'photo-34',
    src: 'photos/photo-34.jpg',
    alt: 'Three Shinto priests in white robes walk toward a shrine pavilion among trees',
    location: 'Tokyo, Japan',
    width: 960,
    height: 1440,
  },
  {
    slug: 'photo-35',
    src: 'photos/photo-35.jpg',
    alt: 'A person in a red jacket walks down a neon-lit night street crowded with signs',
    location: 'Tokyo, Japan',
    width: 960,
    height: 1440,
  },
  {
    slug: 'photo-36',
    src: 'photos/photo-36.jpg',
    alt: 'Pedestrians cross a busy city intersection lined with modern facades at dusk',
    location: 'Tokyo, Japan',
    width: 1440,
    height: 960,
  },
  {
    slug: 'photo-37',
    src: 'photos/photo-37.jpg',
    alt: 'A red concept sports car on a showroom floor, a second car behind glass',
    location: 'Tokyo, Japan',
    width: 960,
    height: 1440,
  },
  {
    slug: 'photo-38',
    src: 'photos/photo-38.jpg',
    alt: 'Silhouettes move among hanging strands of colored light in a dark immersive installation',
    location: 'Tokyo, Japan',
    width: 1440,
    height: 960,
  },
]
