import type { ArtifactInput } from '@/lib/artifacts'

export const artifactsManifest: ArtifactInput[] = [
  {
    slug: 'lem-login',
    title: 'WebGL Shaders',
    date: '2026-07-15',
    mode: 'light',
    video: 'https://videos.francois.works/artifacts/lem-login/lem-login.mp4',
    poster: 'https://videos.francois.works/artifacts/lem-login/lem-login-poster.jpg',
    width: 720,
    height: 410,
    kind: 'showcase',
  },
  {
    slug: 'toolbar',
    title: 'React + Motion',
    date: '2026-07-15',
    mode: 'dark',
    video: 'https://videos.francois.works/artifacts/toolbar/toolbar.mp4',
    poster: 'https://videos.francois.works/artifacts/toolbar/toolbar-poster.jpg',
    width: 720,
    height: 720,
    kind: 'showcase',
  },
  {
    slug: 'scribble-strikethrough',
    title: 'SVG Path Generation',
    date: '2026-07-13',
    mode: 'dark',
    video: 'https://videos.francois.works/artifacts/scribble-list/scribble-list.mp4',
    poster: 'https://videos.francois.works/artifacts/scribble-list/scribble-list-poster.jpg',
    width: 720,
    height: 782,
    kind: 'demo',
  },
  {
    slug: 'player',
    title: 'React + Motion',
    date: '2026-06-08',
    mode: 'dark',
    video: 'https://videos.francois.works/artifacts/tape-player/tape-player.mp4',
    poster: 'https://videos.francois.works/artifacts/tape-player/tape-player-poster.jpg',
    width: 720,
    height: 720,
    kind: 'demo',
  },
]
